# environment variables mapping
# https://github.com/node-config/node-config/wiki/Environment-Variables#custom-environment-variables

server:
  # The port on which this backend service is started.
  port:
    __name: PORT
    __format: number

  # The path on which this backend service is served.
  basePath: BASE_PATH

core:
  project:
    # The API key of the CaaS instance for different viewing modes.
    apiKey:
      # Master API key for both viewing modes. All non-set apiKeys will default to this one.
      master: MASTER_KEY

      # The API key of the CaaS instance for preview viewing mode. Leave blank when providing a master key.
      preview: PREVIEW_KEY

      # The API key of the CaaS instance for release viewing mode. Leave blank when providing a master key.
      release: RELEASE_KEY

    # The URL of the navigation service.
    navigationServiceURL: NAVIGATION_SERVICE_URL

    # The URL of the CaaS instance.
    caasURL: CAAS_URL

    # The ID of the CaaS project.
    projectID: PROJECT_ID

    # The tenant ID of the CaaS project.
    tenantID: TENANT_ID

  # The base URL of the server running the Content Creator.
  fsServerOrigin: FS_SERVER_ORIGIN

  # A fallback locale used if any request is received without explicit locale. Has to have format like in 'de_DE'
  defaultLocale: DEFAULT_LOCALE

  # Numeric representation of logLevels:
  # DEBUG = 0, INFO = 1, WARNING = 2, ERROR = 3, NONE = 4
  logLevel:
    __name: LOG_LEVEL
    __format: number