# This file contains the mandatory configuration. It can be changed or overridden by subsequent files.
# Learn more about the loading order of overriding files with the link below.
# To configure your setup, add config files with this naming convention without uploading to Git (they are ignored by default)
# https://github.com/node-config/node-config/wiki/Configuration-Files#file-load-order

server:
  # The port on which this backend service is started.
  port: 3001

  # The path on which this backend service is served.
  basePath: /api

  # Specify Swagger UI serving
  docs:
    # Whether to serve Swagger UI
    enabled: false

    # Path on which the Swagger UI should be served
    basePath: /docs

  # Providing SSL Encryption for risen browser requirements
  ssl:
    # Use SSL?
    enabled: false

core:
  project:
    # Customize several names of form fields.
    fields:
      # Name of the field for storing the ShopID
      id: id

      # Name of the field for storing the type of page represented in a FirstSpirit page.
      type: type

  # Numeric representation of logLevels:
  # DEBUG = 0, INFO = 1, WARNING = 2, ERROR = 3, NONE = 4
  logLevel: 1