# to configure your setup, add config files with this naming convention without uploading to Git (they are ignored by default)
# https://github.com/node-config/node-config/wiki/Configuration-Files#file-load-order

server:
  # The port on which this backend service is started.
  port: 3001

  # The path on which this backend service is served.
  basePath: /api

  # Providing SSL Encryption for risen browser requirements
  ssl:
    # Use SSL?
    enabled: false

    # The path to the SSL Key file
    key:

    # The path to the SSL Certificate file
    cert:

core:
  project:
    # The API key of the CaaS instance for different viewing modes.
    # As a best practice, define one API key for the preview mode, applicable to both the main project and, if applicable, any other remote project. The same principle applies to the release key.
    apiKey:
      # Master API key for both viewing modes. It is used for both viewing modes and acts as a fallback when either the preview key or the release key is not provided.
      master: &master aaaaaaaa-bbbb-cccc-dddd-eeeeeeee

      # The API key of the CaaS instance for preview viewing mode. Leave blank when providing a master key.
      preview: *master # (use reference or leave blank when providing a master key)

      # The API key of the CaaS instance for release viewing mode. Leave blank when providing a master key.
      release: *master # (use reference or leave blank when providing a master key)

    # Optional
    # Specify projects with referenced media objects.
    remotes:
      media:
        id: aaaaaaaa-bbbb-cccc-dddd-eeeeeeee
        locale: de_DE

    # The URL of the navigation service.
    navigationServiceURL: https://example.org/NavigationService

    # The URL of the CaaS instance.
    caasURL: https://example.org/CaaS

    # The ID of the CaaS project.
    projectID: aaaaaaaa-bbbb-cccc-dddd-eeeeeeee

    # The tenant ID of the CaaS project.
    tenantID: tenant-id

    # Whether untranslated sections should be filtered out.
    removeUntranslatedSections: false

    # For secure communication between FSM and FE API Backend to make ShareView mode possible, there is an encrypted and signed way to exchange information.
    shareView:

      # Secret for decrypting token and verifying its integrity. It must be base64 encoded.
      secret: 'i-am-a-secret'

  # The base URL of the server running the Content Creator.
  fsServerOrigin: https://example.org/FSServerOrigin

  # A fallback locale used if any request is received without explicit locale. Has to have format like in de_DE
  defaultLocale: de_DE

  # Numeric representation of logLevels:
  # DEBUG = 0, INFO = 1, WARNING = 2, ERROR = 3, NONE = 4
  logLevel: 0
